// old/WEB/makemyresume/src/app/components/Navigation/NavigationComponent.jsx
import { useMsal } from "@azure/msal-react";
import { Link } from "react-router-dom";
import { loginRequest } from "../../msal/msalConfig";

export function NavigationComponent() {
  const { instance } = useMsal();

  function handleLogin(event) {
    instance.loginPopup(loginRequest).catch(e => {
      console.log(e);
    });
  }
  return (
    <nav className="navbar navbar-expand-lg navbar-dark bg-primary">
      <div className="container-fluid">
        <Link className="navbar-brand" to="/">Make My Resume</Link>
        <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navBarMain" aria-controls="navBarMain" aria-expanded="false" aria-label="Toggle navigation">
          <span className="navbar-toggler-icon"></span>
        </button>
        <div className="collapse navbar-collapse" id="navBarMain">
          <ul className="navbar-nav me-auto mb-2 mb-lg-0">
            <li className="nav-item">
              <Link className="nav-link" aria-current="page" to="/">Home</Link>
            </li>
            <li className="nav-item">
              <Link className="nav-link" to="/about">About</Link>
            </li>
            <li className="nav-item">
              <Link className="nav-link" to="/authtest">Auth Test</Link>
            </li>
          </ul>
          <form className="d-flex" role="login">
            <button className="btn btn-outline-success" type="button" onClick={handleLogin}>Login</button>
          </form>
        </div>
      </div>
    </nav>
  );
}

// old/WEB/makemyresumeng/src/app/components/Navigation/navigation.component.ts
import { Component, OnInit } from '@angular/core';
import { MsalService } from '@azure/msal-angular';
import { AuthenticationResult } from '@azure/msal-browser';

@Component({
  selector: 'app-navigation',
  templateUrl: './navigation.component.html',
  styleUrls: ['./navigation.component.css']
})
export class NavigationComponent implements OnInit {

  constructor(private authService: MsalService) { }

  ngOnInit(): void {

  }

  isLoggedIn(): boolean {
    return this.authService.instance.getActiveAccount() != null;
  }

  login() {
    this.authService.loginPopup()
    .subscribe((response: AuthenticationResult) => {
      this.authService.instance.setActiveAccount(response.account);
    });
  }

  logout() {
    this.authService.logout();
  }

}

<nav class="navbar navbar-expand-lg navbar-dark bg-unosquare">
    <div class="container-fluid">
        <a class="navbar-brand" routerLink="/home">🦄 MakeMyResume</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01"
            aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" routerLink="/home" routerLinkActive="active" ariaCurrentWhenActive="page">Home</a>
                </li>
                <li *ngIf="isLoggedIn()" class="nav-item">
                    <a class="nav-link" routerLink="/resumes" routerLinkActive="active" ariaCurrentWhenActive="page">My Resume</a>
                </li>
                <li *ngIf="isLoggedIn()" class="nav-item">
                    <a class="nav-link" routerLink="/admin-panel" routerLinkActive="active" ariaCurrentWhenActive="page">Admin Panel</a>
                </li>
            </ul>
            <ul *ngIf="isLoggedIn()" class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link active" (click)="logout()" routerLink="/home">Logout</a>
                </li>
            </ul>
            <ul *ngIf="!isLoggedIn()" class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link active" (click)="login()" routerLink="/home">Login</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
